export const initialScenarios = {
  // ATTIVITÀ 1: GESTIONE DELLE EMOZIONI (SITUAZIONI STIMOLO)
  // Obiettivo: Proiezione emotiva senza suggerimenti.
  emotions: [
    { id: 1, text: "Il professore consegna le verifiche. Tu hai studiato ogni pomeriggio per due settimane e leggi '5' sul tuo foglio. Il compagno accanto a te, che ti ha chiesto suggerimenti tutto il tempo, ha preso '8'.", tags: ["scuola"] },
    { id: 2, text: "Apro Instagram e vedi una foto di tutto il tuo gruppo di amici a cena fuori. Nessuno ti ha scritto o invitato.", tags: ["sociale"] },
    { id: 3, text: "Rientri a casa e trovi tua madre che piange in cucina. Appena ti vede, si asciuga le lacrime e inizia a preparare la cena in silenzio.", tags: ["famiglia"] },
    { id: 4, text: "Sei in corridoio. Passa la persona che ti piace, ti guarda per un secondo negli occhi e poi distoglie lo sguardo parlando con qualcun altro.", tags: ["relazioni"] },
    { id: 5, text: "Un tuo amico fa una battuta pesante su di te davanti agli altri. Tutti ridono, incluso lui che ti guarda aspettando che rida anche tu.", tags: ["amicizia"] },
    { id: 6, text: "Hai appena inviato un messaggio importante e vulnerabile a un amico. Vedi le spunte blu di visualizzazione, ma dopo due ore non c'è ancora risposta.", tags: ["comunicazione"] },
    { id: 7, text: "Ti guardi allo specchio prima di uscire. L'immagine riflessa non assomiglia per niente alle foto che vedi nel tuo feed di TikTok.", tags: ["immagine di sé"] },
    { id: 8, text: "L'allenatore legge la lista dei convocati per la partita importante. Il tuo nome non c'è.", tags: ["performance"] },
    { id: 9, text: "Un compagno ti confida un segreto grave che riguarda la salute di un altro amico, facendoti giurare di non dirlo a nessuno.", tags: ["responsabilità"] },
    { id: 10, text: "Sei a una festa. Qualcuno rovescia un drink addosso a te macchiandoti vistosamente i vestiti. La musica si ferma e si girano tutti.", tags: ["sociale"] },
    { id: 11, text: "Tuo padre entra in camera tua senza bussare e inizia a leggere il diario/quaderno che avevi lasciato aperto sulla scrivania.", tags: ["privacy"] },
    { id: 12, text: "Hai preso un voto altissimo a un compito difficile. I tuoi compagni iniziano a dire che sei il 'cocco' del professore.", tags: ["giudizio"] },
    { id: 13, text: "Il tuo cane, che hai da quando eri piccolo, stamattina non riusciva ad alzarsi dalla cuccia.", tags: ["perdita"] },
    { id: 14, text: "Stai camminando per strada da solo/a. Senti dei passi veloci dietro di te che si avvicinano sempre di più.", tags: ["sicurezza"] },
    { id: 15, text: "Durante un'interrogazione, fai scena muta su una domanda che sapevi perfettamente. Il professore ti guarda in attesa.", tags: ["performance"] },
    { id: 16, text: "Un amico ti restituisce un oggetto a cui tenevi molto, ma è rotto.", tags: ["fiducia"] },
    { id: 17, text: "Senti i tuoi genitori discutere animatamente in salotto. Uno dei due pronuncia la parola 'separazione'.", tags: ["famiglia"] },
    { id: 18, text: "Hai preparato una sorpresa per il compleanno del tuo partner. Lui/lei reagisce dicendo: 'Ah, grazie', e la mette da parte.", tags: ["aspettative"] },
    { id: 19, text: "Vedi il tuo ex camminare mano nella mano con un'altra persona, ridendo come faceva con te.", tags: ["relazioni"] },
    { id: 20, text: "Il professore ti accusa di aver copiato davanti a tutta la classe. Tu non l'hai fatto.", tags: ["ingiustizia"] },
    { id: 21, text: "Devi parlare in pubblico davanti a tutta la scuola per un'assemblea. Sali sul palco e il microfono fischia.", tags: ["esposizione"] },
    { id: 22, text: "Un amico ti chiede soldi in prestito per la terza volta. Non ti ha mai restituito quelli precedenti.", tags: ["confini"] },
    { id: 23, text: "Trovi il tuo profilo social clonato da qualcuno che posta cose ridicole a tuo nome.", tags: ["identità"] },
    { id: 24, text: "Sei stato invitato a due feste diverse per la stessa sera da due gruppi di amici che non si sopportano.", tags: ["scelta"] },
    { id: 25, text: "Un adulto ti fa un complimento sul tuo aspetto fisico che dura qualche secondo di troppo.", tags: ["ambiguità"] },
    { id: 26, text: "Hai finalmente comprato le scarpe che desideravi da mesi. A scuola qualcuno ti dice che sono 'già passate di moda'.", tags: ["omologazione"] },
    { id: 27, text: "Il tuo migliore amico inizia a frequentare un gruppo di persone che a te non piace e smette di scriverti.", tags: ["cambiamento"] },
    { id: 28, text: "Sei a casa da solo/a. Senti un rumore forte provenire dal piano di sopra.", tags: ["sicurezza"] },
    { id: 29, text: "Ti viene affidato un compito di grande responsabilità dal preside. Non sei sicuro di saperlo fare.", tags: ["responsabilità"] },
    { id: 30, text: "Vedi un compagno bullizzare un ragazzo più piccolo in un angolo del cortile. Nessun altro sta guardando.", tags: ["spettatore"] }
  ],

  // ATTIVITÀ 2: PRENDERE DECISIONI (A FREDDO)
  decisions_cold: [
    { id: 1, text: "Devi scegliere la scuola superiore. I tuoi premono per il Liceo Classico, tu vuoi fare l'Istituto d'Arte. Sai che la retta dell'Istituto d'Arte è costosa e la tua famiglia è in difficoltà economica.", tags: ["futuro"] },
    { id: 2, text: "Un tuo amico ti confida di essere omosessuale. Un altro amico del gruppo, ignaro, fa spesso battute omofobe. L'amico che ha fatto coming out sta iniziando a isolarsi.", tags: ["sociale"] },
    { id: 3, text: "Hai notato che la tua migliore amica salta spesso i pasti e ha perso molto peso velocemente. Ti ha fatto promettere di non dirlo a nessuno, minacciando di chiudere l'amicizia.", tags: ["salute"] },
    { id: 4, text: "Trovi le risposte della verifica finale di matematica dimenticate sulla cattedra. Nessuno ti vede. Hai la media del 5.", tags: ["etica"] },
    { id: 5, text: "Ti offrono un lavoretto estivo ben pagato che però coincide con le date del viaggio che avevi pianificato con i tuoi amici da mesi.", tags: ["priorità"] },
    { id: 6, text: "Un compagno di classe viene sistematicamente escluso dal gruppo WhatsApp della classe. Nessuno lo insulta, semplicemente viene ignorato. Tu sei amministratore del gruppo.", tags: ["inclusione"] },
    { id: 7, text: "Hai rotto il telefono di un amico per sbaglio. Lui pensa che si sia rotto da solo perché era già vecchio. Non hai i soldi per ripagarlo.", tags: ["onestà"] },
    { id: 8, text: "I tuoi amici organizzano un furto in un negozio 'per gioco'. Ti chiedono di fare il palo. Dicono che se non lo fai sei un codardo.", tags: ["pressione"] },
    { id: 9, text: "Scopri che il ragazzo della tua amica la tradisce. Se glielo dici, lei soffrirà moltissimo e potrebbe non crederti.", tags: ["verità"] },
    { id: 10, text: "Sei stato accettato in una squadra sportiva prestigiosa, ma gli allenamenti ti costringerebbero a lasciare il corso di teatro che ami.", tags: ["identità"] },
    { id: 11, text: "Un professore fa commenti politici in classe che ti offendono profondamente. Se rispondi, temi ripercussioni sui voti.", tags: ["autorità"] },
    { id: 12, text: "Vedi un amico copiare durante un esame importante. Il professore dice che se scopre qualcuno copiare, annullerà il compito a tutta la classe.", tags: ["dilemma"] },
    { id: 13, text: "I tuoi genitori ti vietano di frequentare una persona. Tu sai che è una brava persona, ma ha una cattiva reputazione in paese.", tags: ["autonomia"] },
    { id: 14, text: "Hai trovato un portafoglio con 100 euro e i documenti. Sai di chi è: è di un ragazzo antipatico che ti prende sempre in giro.", tags: ["vendetta/etica"] },
    { id: 15, text: "Un amico posta foto modificate sui social fingendo di avere una vita che non ha. Stai notando che sta perdendo il contatto con la realtà.", tags: ["realtà"] },
    { id: 16, text: "Devi fare un lavoro di gruppo. Il tuo migliore amico vuole stare con te, ma sai che non lavorerà e abbasserà il voto. Un altro compagno molto bravo ti ha chiesto di unirti a lui.", tags: ["amicizia/dovere"] },
    { id: 17, text: "Ti accorgi che un adulto di riferimento (allenatore/insegnante) ha un comportamento troppo confidenziale con un tuo compagno.", tags: ["protezione"] },
    { id: 18, text: "Sei vegetariano. A una cena formale a casa dei nonni del tuo partner servono solo carne. Non vuoi offenderli.", tags: ["adattamento"] },
    { id: 19, text: "Un amico inizia a fumare e ti chiede di non dirlo ai suoi. I suoi genitori ti chiedono esplicitamente se sai qualcosa.", tags: ["lealtà"] },
    { id: 20, text: "Hai la possibilità di studiare all'estero per un anno, ma dovresti lasciare il tuo partner attuale.", tags: ["distanza"] }
  ],

  // ATTIVITÀ 3: PRENDERE DECISIONI (A CALDO)
  decisions_hot: [
    { id: 1, text: "Sei in macchina. Chi guida ha bevuto, sta andando troppo forte e ride quando gli chiedi di rallentare. C'è una curva avanti.", tags: ["pericolo"] },
    { id: 2, text: "Sei a una festa. Un ragazzo/a sta palesemente male per l'alcol. I suoi amici dicono 'lascialo stare, deve smaltire', ma ha gli occhi rovesciati.", tags: ["emergenza"] },
    { id: 3, text: "Sei in un negozio. Il tuo amico infila un profumo costoso nel tuo zaino senza che tu possa reagire e si avvia all'uscita. La sicurezza vi guarda.", tags: ["panico"] },
    { id: 4, text: "Durante una partita, un avversario ti sputa addosso mentre l'arbitro è girato.", tags: ["provocazione"] },
    { id: 5, text: "Arriva un messaggio sul gruppo classe: è una foto nuda di una tua compagna. Qualcuno scrive 'Folla la inoltro a tutti'. Hai il telefono in mano.", tags: ["cyberbullismo"] },
    { id: 6, text: "Sei su un autobus affollato. Senti una mano che ti tocca insistentemente. Non riesci a muoverti.", tags: ["difesa"] },
    { id: 7, text: "Torni a casa prima del previsto e senti dei rumori strani provenire da camera tua.", tags: ["ignoto"] },
    { id: 8, text: "Sei a un concerto nella calca. Qualcuno cade e si crea un vuoto, la gente inizia a spingere e ti manca l'aria.", tags: ["folla"] },
    { id: 9, text: "Un amico ti offre una pasticca in discoteca: 'Prendila, l'abbiamo presa tutti, non fare il bambino'. Ti mette la mano aperta davanti alla faccia.", tags: ["pressione"] },
    { id: 10, text: "Vedi due ragazzi che stanno picchiando selvaggiamente un cane in un vicolo cieco.", tags: ["azione"] },
    { id: 11, text: "Il tuo partner ti strappa il telefono di mano urlando perché hai ricevuto un messaggio da un numero che non conosce.", tags: ["aggressività"] },
    { id: 12, text: "Sei a scuola. Scatta l'allarme antincendio. Tutti pensano sia un'esercitazione, ma tu senti odore di fumo vero.", tags: ["reazione"] },
    { id: 13, text: "Stai camminando. Un'auto rallenta al tuo fianco e il conducente ti chiede di avvicinarti per un'informazione, ma ha un atteggiamento strano.", tags: ["istinto"] },
    { id: 14, text: "Fai cadere per sbaglio il computer del professore mentre passi vicino alla cattedra. Lo schermo si crepa. Non ti ha visto nessuno, ma la lezione inizia tra un minuto.", tags: ["responsabilità"] },
    { id: 15, text: "Un amico ti confessa in lacrime che sta pensando di farla finita. È sul tetto di un palazzo in videochiamata.", tags: ["crisi"] },
    { id: 16, text: "Sei al mare. Vedi qualcuno che si sbraccia al largo, poi va sotto. Nessun altro sembra averlo visto.", tags: ["soccorso"] },
    { id: 17, text: "Il tuo ex partner si presenta sotto casa tua urlando e prendendo a calci il portone.", tags: ["minaccia"] },
    { id: 18, text: "Sei a cena con i genitori del tuo partner. Il padre fa un commento apertamente razzista/sessista e tutti ti guardano aspettando la tua reazione.", tags: ["confronto"] },
    { id: 19, text: "Stai guidando il motorino. Un'auto ti taglia la strada e il conducente scende con una mazza in mano.", tags: ["violenza"] },
    { id: 20, text: "Trovi una pistola nello zaino di un tuo compagno di classe.", tags: ["sicurezza"] }
  ],

  // ATTIVITÀ 4: NARRAZIONE EMOTIVA (VOCABOLARIO)
  emotion_narratives: [
    { id: 1, text: "Vulnerabile" }, { id: 2, text: "Disperato" }, { id: 3, text: "Colpevole" }, { id: 4, text: "Depresso" },
    { id: 5, text: "Inferiore" }, { id: 6, text: "Abbandonato" }, { id: 7, text: "Isolato" }, { id: 8, text: "Apatico" },
    { id: 9, text: "Ottimista" }, { id: 10, text: "Intimo" }, { id: 11, text: "Orgoglioso" }, { id: 12, text: "Accettato" },
    { id: 13, text: "Ispirato" }, { id: 14, text: "Curioso" }, { id: 15, text: "Liberato" }, { id: 16, text: "Speranzoso" },
    { id: 17, text: "Frustrato" }, { id: 18, text: "Aggressivo" }, { id: 19, text: "Minacciato" }, { id: 20, text: "Critico" },
    { id: 21, text: "Distante" }, { id: 22, text: "Ostile" }, { id: 23, text: "Provocato" }, { id: 24, text: "Sospettoso" },
    { id: 25, text: "Insicuro" }, { id: 26, text: "Ansioso" }, { id: 27, text: "Sottomesso" }, { id: 28, text: "Respinto" },
    { id: 29, text: "Umiliato" }, { id: 30, text: "Inadeguato" }, { id: 31, text: "Alienato" }, { id: 32, text: "Spaventato" },
    { id: 33, text: "Deluso" }, { id: 34, text: "Disapprovazione" }, { id: 35, text: "Giudicante" }, { id: 36, text: "Ripugnante" },
    { id: 37, text: "Evitante" }, { id: 38, text: "Confuso" }, { id: 39, text: "Stupito" }, { id: 40, text: "Eccitato" },
    { id: 41, text: "Disilluso" }, { id: 42, text: "Perplesso" }, { id: 43, text: "Nostalgico" }, { id: 44, text: "Sollievo" },
    { id: 45, text: "Gratitudine" }, { id: 46, text: "Serenità" }, { id: 47, text: "Euforia" }, { id: 48, text: "Malinconia" }
  ],

  // ATTIVITÀ 5: AFFETTIVITÀ E SESSUALITÀ
  affectivity_sexuality: [
    { id: 1, text: "Siete in un momento di intimità. Il partner prova a fare qualcosa di nuovo senza chiedertelo prima.", tags: ["consenso"] },
    { id: 2, text: "Il tuo partner vuole guardare il contenuto del tuo telefono ogni sera.", tags: ["privacy"] },
    { id: 3, text: "Ricevi una foto intima non richiesta su Instagram da qualcuno che conosci appena.", tags: ["digital"] },
    { id: 4, text: "Il tuo partner ti dice: 'Se mi amassi davvero, non usciresti con i tuoi amici stasera'.", tags: ["manipolazione"] },
    { id: 5, text: "Durante una discussione, esprimi un tuo disagio e l'altro risponde: 'Ti inventi sempre le cose, sei pazzo/a'.", tags: ["gaslighting"] },
    { id: 6, text: "Hai dei dubbi sul tuo orientamento sessuale. A casa senti spesso battute offensive su questo argomento.", tags: ["identità"] },
    { id: 7, text: "Il preservativo si rompe durante un rapporto.", tags: ["imprevisto"] },
    { id: 8, text: "Un amico ti abbraccia o ti tocca spesso in modo fisico che ti infastidisce, anche se dice che scherza.", tags: ["confini"] },
    { id: 9, text: "Ti piace una persona, ma i tuoi amici dicono che 'non è abbastanza' per te per via del suo aspetto.", tags: ["giudizio"] },
    { id: 10, text: "Il partner ti riempie di regali e messaggi d'amore dopo due giorni che vi conoscete (love bombing), ma sparisce se non rispondi subito.", tags: ["dinamiche"] },
    { id: 11, text: "Vuoi aspettare per avere un rapporto sessuale, ma il partner dice che 'tutti alla nostra età lo fanno'.", tags: ["pressione"] },
    { id: 12, text: "Scopri che una tua foto privata sta girando in una chat di classe.", tags: ["privacy"] },
    { id: 13, text: "Ti senti attratto/a da qualcuno che non è il tuo partner.", tags: ["fedeltà"] },
    { id: 14, text: "Il partner commenta negativamente come ti vesti prima di uscire.", tags: ["controllo"] },
    { id: 15, text: "Dopo un rapporto sessuale, ti senti triste o vuoto/a invece che felice.", tags: ["vissuto"] },
    { id: 16, text: "Un adulto ti fa complimenti sul fisico che ti mettono a disagio.", tags: ["grooming"] },
    { id: 17, text: "Il partner minaccia di farsi del male se lo/la lasci.", tags: ["manipolazione"] },
    { id: 18, text: "Non provi interesse per il sesso, mentre tutti i tuoi amici ne parlano continuamente.", tags: ["identità"] },
    { id: 19, text: "Hai avuto un rapporto non protetto e ora hai paura di fare il test o parlarne con qualcuno.", tags: ["salute"] },
    { id: 20, text: "Il tuo partner vuole filmarvi mentre fate l'amore. Tu non sei convinto/a.", tags: ["consenso"] },
    { id: 21, text: "Ti senti dire che 'gli uomini/le donne sono fatti così' per giustificare un comportamento che ti ha ferito.", tags: ["stereotipi"] },
    { id: 22, text: "Usi un'app di incontri. La persona insiste per vedersi subito a casa sua.", tags: ["sicurezza"] },
    { id: 23, text: "Il partner racconta dettagli intimi della vostra relazione agli amici senza il tuo permesso.", tags: ["riservatezza"] },
    { id: 24, text: "Stai frequentando qualcuno molto più grande di te che ti dice che sei 'molto maturo/a per la tua età'.", tags: ["potere"] },
    { id: 25, text: "Ti accorgi che la pornografia sta influenzando quello che ti aspetti dal sesso reale.", tags: ["immaginario"] },
    { id: 26, text: "Il partner ti chiede di smettere di seguire certe persone su Instagram.", tags: ["gelosia"] },
    { id: 27, text: "Ti senti obbligato/a a rispondere ai messaggi del partner immediatamente, a qualsiasi ora.", tags: ["disponibilità"] },
    { id: 28, text: "Durante un rapporto dici 'basta' e l'altro insiste o si offende.", tags: ["consenso"] },
    { id: 29, text: "Ti piace qualcuno che è già impegnato e questa persona ti dà corda.", tags: ["rispetto"] },
    { id: 30, text: "Ti senti solo/a anche quando sei con il tuo partner.", tags: ["connessione"] }
  ],

  // ATTIVITÀ 6: COMUNICAZIONE EFFICACE (PASSIVA, AGGRESSIVA, ASSERTIVA)
  effective_communication: [
    { id: 1, text: "Un tuo compagno ti chiede di fargli copiare i compiti per l'ennesima volta. Tu hai passato il pomeriggio a studiare e rispondi a testa bassa: 'Vabbè dai, prendi pure il quaderno... basta che non se ne accorga il prof.'", tags: ["passiva", "scuola"] },
    { id: 2, text: "Un amico arriva con 40 minuti di ritardo al vostro appuntamento senza avvisare. Appena lo vedi gli urli contro davanti a tutti: 'Sei sempre il solito egoista irresponsabile! Fai schifo, non ti azzardare mai più a farmi aspettare!'", tags: ["aggressiva", "amicizia"] },
    { id: 3, text: "In un lavoro di gruppo, un compagno non ha svolto la parte assegnata. Gli dici con calma: 'Ho notato che manca la tua parte e la consegna è domani. Mi preoccupa non finire in tempo: come possiamo riorganizzarci adesso?'", tags: ["assertiva", "collaborazione"] },
    { id: 4, text: "Il gruppo decide di andare in una pizzeria che non ti piace affatto e dove i prezzi sono troppo alti per te. Ti chiedono se va bene e dici: 'Sì sì, per me è uguale, fate voi...'", tags: ["passiva", "gruppo"] },
    { id: 5, text: "Il tuo compagno di banco continua a picchiettare rumorosamente con la penna mentre stai facendo una verifica. Ti volti di scatto, gli strappi la penna e la lanci per terra dicendo: 'Smettila deficiente!'", tags: ["aggressiva", "scuola"] },
    { id: 6, text: "Un amico ti fa una battuta sul tuo modo di vestire che ti ferisce. Lo prendi da parte e gli dici: 'Capisco che per te fosse una battuta, ma quel commento mi ha dato fastidio. Ti chiedo di non rifarlo.'", tags: ["assertiva", "confini"] },
    { id: 7, text: "Tua madre ti assegna un compito domestico proprio mentre avevi pianificato di riposarti un'ora dopo una settimana pesante. Sospiri, non dici nulla, ma passi il resto della giornata rispondendo a monosillabi e sbattendo le porte.", tags: ["passiva-aggressiva", "famiglia"] },
    { id: 8, text: "Sei in coda alla mensa o al bar e qualcuno ti passa sfacciatamente davanti. Tu lo guardi dritto negli occhi e gli dici con tono fermo: 'Scusa, la fila inizia dietro. Stavamo aspettando il nostro turno.'", tags: ["assertiva", "rispetto"] },
    { id: 9, text: "Un insegnante valuta un tuo compito con un voto che ritieni ingiusto rispetto ai criteri spiegati. A fine lezione chiedi con cortesia: 'Professore, potremmo rivedere insieme gli errori? Vorrei capire meglio cosa migliorare rispetto agli obiettivi.'", tags: ["assertiva", "scuola"] },
    { id: 10, text: "Un compagno ti accusa falsamente di aver sparso una voce su di lui. Tu scoppi a piangere, ti scusi anche se non hai fatto nulla e ti chiudi in bagno per evitare lo scontro.", tags: ["passiva", "conflitto"] },
    { id: 11, text: "Sei stanco e vuoi andare a casa, ma i tuoi amici insistono per restare ancora. Dici con fermezza e un sorriso: 'Ragazzi, mi sono divertito molto ma sono davvero stanco. Stasera vado, ci vediamo domani!'", tags: ["assertiva", "autonomia"] },
    { id: 12, text: "Durante una discussione su un argomento controverso, un compagno esprime un'opinione opposta alla tua. Tu alzi la voce: 'Ma cosa dici? Non capisci niente, la tua idea è una stupidaggine totale!'", tags: ["aggressiva", "dialogo"] },
    { id: 13, text: "Un amico ti chiede in prestito la tua giacca preferita. Non ti va di prestarla perché hai paura si rovini, ma rispondi: 'Mah... se proprio ti serve... spero solo non succeda niente.'", tags: ["passiva", "confini"] },
    { id: 14, text: "Un tuo amico continua a interromperti mentre stai raccontando qualcosa che per te è molto importante. Ti fermi e dici con calma: 'Vorrei finire di raccontarti questa cosa prima di sentire il tuo parere, mi dai un minuto?'", tags: ["assertiva", "ascolto"] },
    { id: 15, text: "Il cameriere porta un piatto completamente diverso da quello che avevi ordinato. Non dici nulla per paura di creare disturbo e mangi solo un pezzo di pane.", tags: ["passiva", "bisogni"] },
    { id: 16, text: "In palestra qualcuno occupa l'attrezzo per guardare il telefono per 15 minuti. Ti avvicini e gli gridi: 'Ehi ti svegli? Non sei a casa tua, levati di mezzo!'", tags: ["aggressiva", "convivenza"] },
    { id: 17, text: "Un amico ti chiede di accompagnarlo a fare shopping, ma hai già un altro impegno. Rispondi: 'Oggi ho già preso un impegno e non posso. Sabato prossimo però sono libero, ti andrebbe di andarci allora?'", tags: ["assertiva", "gestione del tempo"] },
    { id: 18, text: "Qualcuno fa un complimento sincero a un tuo lavoro. Tu arrossisci e dici: 'Ma no dai, fa schifo, è venuto male per puro caso...'", tags: ["passiva", "autostima"] },
    { id: 19, text: "Un tuo compagno di progetto prende tutti i meriti davanti agli altri per un'idea che è stata tua. Davanti a tutti dici con tranquillità: 'Sono felice che l'idea piaccia, ci ho lavorato molto ieri sera per impostarla.'", tags: ["assertiva", "riconoscimento"] },
    { id: 20, text: "Tuo fratello prende le tue cose senza chiedere permesso. Gli dici urlando: 'Sei un ladro! Non toccare mai più niente o ti distruggo tutto quello che hai!'", tags: ["aggressiva", "famiglia"] }
  ]
};